//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodeCaptureSettingsSample.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BarcodeCaptureSettingsSample.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Setting_View {
            get {
                return ResourceManager.GetString("Setting_View", resourceCulture);
            }
        }
        
        internal static string Setting_Camera {
            get {
                return ResourceManager.GetString("Setting_Camera", resourceCulture);
            }
        }
        
        internal static string Setting_BarcodeCapture {
            get {
                return ResourceManager.GetString("Setting_BarcodeCapture", resourceCulture);
            }
        }
        
        internal static string Setting_Result {
            get {
                return ResourceManager.GetString("Setting_Result", resourceCulture);
            }
        }
        
        internal static string Setting_ScanArea {
            get {
                return ResourceManager.GetString("Setting_ScanArea", resourceCulture);
            }
        }
        
        internal static string Setting_PointOfInterest {
            get {
                return ResourceManager.GetString("Setting_PointOfInterest", resourceCulture);
            }
        }
        
        internal static string Setting_Overlay {
            get {
                return ResourceManager.GetString("Setting_Overlay", resourceCulture);
            }
        }
        
        internal static string Setting_Viewfinder {
            get {
                return ResourceManager.GetString("Setting_Viewfinder", resourceCulture);
            }
        }
        
        internal static string Setting_Logo {
            get {
                return ResourceManager.GetString("Setting_Logo", resourceCulture);
            }
        }
        
        internal static string Setting_Gestures {
            get {
                return ResourceManager.GetString("Setting_Gestures", resourceCulture);
            }
        }
        
        internal static string Setting_Controls {
            get {
                return ResourceManager.GetString("Setting_Controls", resourceCulture);
            }
        }
        
        internal static string Margins {
            get {
                return ResourceManager.GetString("Margins", resourceCulture);
            }
        }
        
        internal static string Margin_Top {
            get {
                return ResourceManager.GetString("Margin_Top", resourceCulture);
            }
        }
        
        internal static string Margin_Right {
            get {
                return ResourceManager.GetString("Margin_Right", resourceCulture);
            }
        }
        
        internal static string Margin_Bottom {
            get {
                return ResourceManager.GetString("Margin_Bottom", resourceCulture);
            }
        }
        
        internal static string Margin_Left {
            get {
                return ResourceManager.GetString("Margin_Left", resourceCulture);
            }
        }
        
        internal static string ShouldShowScanAreaGuides {
            get {
                return ResourceManager.GetString("ShouldShowScanAreaGuides", resourceCulture);
            }
        }
        
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string Overlay {
            get {
                return ResourceManager.GetString("Overlay", resourceCulture);
            }
        }
        
        internal static string PointOfInterest {
            get {
                return ResourceManager.GetString("PointOfInterest", resourceCulture);
            }
        }
        
        internal static string Brush {
            get {
                return ResourceManager.GetString("Brush", resourceCulture);
            }
        }
        
        internal static string Brush_Defaults {
            get {
                return ResourceManager.GetString("Brush_Defaults", resourceCulture);
            }
        }
        
        internal static string Brush_Red {
            get {
                return ResourceManager.GetString("Brush_Red", resourceCulture);
            }
        }
        
        internal static string Brush_Green {
            get {
                return ResourceManager.GetString("Brush_Green", resourceCulture);
            }
        }
        
        internal static string Brush_Select {
            get {
                return ResourceManager.GetString("Brush_Select", resourceCulture);
            }
        }
        
        internal static string Viewfinder {
            get {
                return ResourceManager.GetString("Viewfinder", resourceCulture);
            }
        }
        
        internal static string Rectangular {
            get {
                return ResourceManager.GetString("Rectangular", resourceCulture);
            }
        }
        
        internal static string WidthAndHeight {
            get {
                return ResourceManager.GetString("WidthAndHeight", resourceCulture);
            }
        }
        
        internal static string WidthAndHeightAspect {
            get {
                return ResourceManager.GetString("WidthAndHeightAspect", resourceCulture);
            }
        }
        
        internal static string HeightAndWidthAspect {
            get {
                return ResourceManager.GetString("HeightAndWidthAspect", resourceCulture);
            }
        }
        
        internal static string ShorterDimensionAndAspect {
            get {
                return ResourceManager.GetString("ShorterDimensionAndAspect", resourceCulture);
            }
        }
        
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        internal static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        internal static string Style_Select {
            get {
                return ResourceManager.GetString("Style_Select", resourceCulture);
            }
        }
        
        internal static string LineStyle {
            get {
                return ResourceManager.GetString("LineStyle", resourceCulture);
            }
        }
        
        internal static string LineStyle_Select {
            get {
                return ResourceManager.GetString("LineStyle_Select", resourceCulture);
            }
        }
        
        internal static string Dimming {
            get {
                return ResourceManager.GetString("Dimming", resourceCulture);
            }
        }
        
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        internal static string Color_Select {
            get {
                return ResourceManager.GetString("Color_Select", resourceCulture);
            }
        }
        
        internal static string DisabledColor {
            get {
                return ResourceManager.GetString("DisabledColor", resourceCulture);
            }
        }
        
        internal static string DisabledColor_Select {
            get {
                return ResourceManager.GetString("DisabledColor_Select", resourceCulture);
            }
        }
        
        internal static string Animation {
            get {
                return ResourceManager.GetString("Animation", resourceCulture);
            }
        }
        
        internal static string Looping {
            get {
                return ResourceManager.GetString("Looping", resourceCulture);
            }
        }
        
        internal static string SizeSpecification {
            get {
                return ResourceManager.GetString("SizeSpecification", resourceCulture);
            }
        }
        
        internal static string SizeSpecification_Select {
            get {
                return ResourceManager.GetString("SizeSpecification_Select", resourceCulture);
            }
        }
        
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        internal static string HeightAspect {
            get {
                return ResourceManager.GetString("HeightAspect", resourceCulture);
            }
        }
        
        internal static string WidthAspect {
            get {
                return ResourceManager.GetString("WidthAspect", resourceCulture);
            }
        }
        
        internal static string ShorterDimension {
            get {
                return ResourceManager.GetString("ShorterDimension", resourceCulture);
            }
        }
        
        internal static string LongerDimensionAspect {
            get {
                return ResourceManager.GetString("LongerDimensionAspect", resourceCulture);
            }
        }
        
        internal static string Aimer {
            get {
                return ResourceManager.GetString("Aimer", resourceCulture);
            }
        }
        
        internal static string FrameColor {
            get {
                return ResourceManager.GetString("FrameColor", resourceCulture);
            }
        }
        
        internal static string FrameColor_Select {
            get {
                return ResourceManager.GetString("FrameColor_Select", resourceCulture);
            }
        }
        
        internal static string DotColor {
            get {
                return ResourceManager.GetString("DotColor", resourceCulture);
            }
        }
        
        internal static string DotColor_Select {
            get {
                return ResourceManager.GetString("DotColor_Select", resourceCulture);
            }
        }
        
        internal static string Laserline {
            get {
                return ResourceManager.GetString("Laserline", resourceCulture);
            }
        }
        
        internal static string EnabledColor {
            get {
                return ResourceManager.GetString("EnabledColor", resourceCulture);
            }
        }
        
        internal static string EnabledColor_Select {
            get {
                return ResourceManager.GetString("EnabledColor_Select", resourceCulture);
            }
        }
        
        internal static string Anchor {
            get {
                return ResourceManager.GetString("Anchor", resourceCulture);
            }
        }
        
        internal static string Anchor_Select {
            get {
                return ResourceManager.GetString("Anchor_Select", resourceCulture);
            }
        }
        
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        internal static string Gestures {
            get {
                return ResourceManager.GetString("Gestures", resourceCulture);
            }
        }
        
        internal static string TapToFocus {
            get {
                return ResourceManager.GetString("TapToFocus", resourceCulture);
            }
        }
        
        internal static string SwipeToZoom {
            get {
                return ResourceManager.GetString("SwipeToZoom", resourceCulture);
            }
        }
        
        internal static string Controls {
            get {
                return ResourceManager.GetString("Controls", resourceCulture);
            }
        }
        
        internal static string TorchButton {
            get {
                return ResourceManager.GetString("TorchButton", resourceCulture);
            }
        }
        
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        internal static string CameraPosition {
            get {
                return ResourceManager.GetString("CameraPosition", resourceCulture);
            }
        }
        
        internal static string DesiredTorchState {
            get {
                return ResourceManager.GetString("DesiredTorchState", resourceCulture);
            }
        }
        
        internal static string DesiredTorchState_Select {
            get {
                return ResourceManager.GetString("DesiredTorchState_Select", resourceCulture);
            }
        }
        
        internal static string CameraSettings {
            get {
                return ResourceManager.GetString("CameraSettings", resourceCulture);
            }
        }
        
        internal static string PreferredResolution {
            get {
                return ResourceManager.GetString("PreferredResolution", resourceCulture);
            }
        }
        
        internal static string PreferredResolution_Select {
            get {
                return ResourceManager.GetString("PreferredResolution_Select", resourceCulture);
            }
        }
        
        internal static string ZoomFactor {
            get {
                return ResourceManager.GetString("ZoomFactor", resourceCulture);
            }
        }
        
        internal static string ZoomGestureZoomFactor {
            get {
                return ResourceManager.GetString("ZoomGestureZoomFactor", resourceCulture);
            }
        }
        
        internal static string FocusGestureStrategy {
            get {
                return ResourceManager.GetString("FocusGestureStrategy", resourceCulture);
            }
        }
        
        internal static string FocusGestureStrategy_Select {
            get {
                return ResourceManager.GetString("FocusGestureStrategy_Select", resourceCulture);
            }
        }
        
        internal static string Setting_Symbologies {
            get {
                return ResourceManager.GetString("Setting_Symbologies", resourceCulture);
            }
        }
        
        internal static string Setting_CompositeTypes {
            get {
                return ResourceManager.GetString("Setting_CompositeTypes", resourceCulture);
            }
        }
        
        internal static string Setting_LocationSelection {
            get {
                return ResourceManager.GetString("Setting_LocationSelection", resourceCulture);
            }
        }
        
        internal static string Setting_Feedback {
            get {
                return ResourceManager.GetString("Setting_Feedback", resourceCulture);
            }
        }
        
        internal static string Setting_CodeDuplicateFilter {
            get {
                return ResourceManager.GetString("Setting_CodeDuplicateFilter", resourceCulture);
            }
        }
        
        internal static string EnableAll {
            get {
                return ResourceManager.GetString("EnableAll", resourceCulture);
            }
        }
        
        internal static string DisableAll {
            get {
                return ResourceManager.GetString("DisableAll", resourceCulture);
            }
        }
        
        internal static string Symbology_Enabled {
            get {
                return ResourceManager.GetString("Symbology_Enabled", resourceCulture);
            }
        }
        
        internal static string Symbology_Disabled {
            get {
                return ResourceManager.GetString("Symbology_Disabled", resourceCulture);
            }
        }
        
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        internal static string ColorInverted {
            get {
                return ResourceManager.GetString("ColorInverted", resourceCulture);
            }
        }
        
        internal static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        internal static string Minimum {
            get {
                return ResourceManager.GetString("Minimum", resourceCulture);
            }
        }
        
        internal static string Minimum_Select {
            get {
                return ResourceManager.GetString("Minimum_Select", resourceCulture);
            }
        }
        
        internal static string Maximum {
            get {
                return ResourceManager.GetString("Maximum", resourceCulture);
            }
        }
        
        internal static string Maximum_Select {
            get {
                return ResourceManager.GetString("Maximum_Select", resourceCulture);
            }
        }
        
        internal static string Extensions {
            get {
                return ResourceManager.GetString("Extensions", resourceCulture);
            }
        }
        
        internal static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        internal static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        internal static string Vibration {
            get {
                return ResourceManager.GetString("Vibration", resourceCulture);
            }
        }
        
        internal static string ScanResult {
            get {
                return ResourceManager.GetString("ScanResult", resourceCulture);
            }
        }
        
        internal static string ContinuousScanning {
            get {
                return ResourceManager.GetString("ContinuousScanning", resourceCulture);
            }
        }
        
        internal static string ResultParametrised_Symbology {
            get {
                return ResourceManager.GetString("ResultParametrised_Symbology", resourceCulture);
            }
        }
        
        internal static string ResultParametrised_SymbolCount {
            get {
                return ResourceManager.GetString("ResultParametrised_SymbolCount", resourceCulture);
            }
        }
        
        internal static string CcResultParametrised_Type {
            get {
                return ResourceManager.GetString("CcResultParametrised_Type", resourceCulture);
            }
        }
        
        internal static string CcResultParametrised_Symbology {
            get {
                return ResourceManager.GetString("CcResultParametrised_Symbology", resourceCulture);
            }
        }
        
        internal static string CcResultParametrised_SymbolCount {
            get {
                return ResourceManager.GetString("CcResultParametrised_SymbolCount", resourceCulture);
            }
        }
    }
}
