//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodeCaptureSettingsSample.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BarcodeCaptureSettingsSample.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aimer.
        /// </summary>
        internal static string Aimer {
            get {
                return ResourceManager.GetString("Aimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor.
        /// </summary>
        internal static string Anchor {
            get {
                return ResourceManager.GetString("Anchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Anchor.
        /// </summary>
        internal static string Anchor_Select {
            get {
                return ResourceManager.GetString("Anchor_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation.
        /// </summary>
        internal static string Animation {
            get {
                return ResourceManager.GetString("Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush.
        /// </summary>
        internal static string Brush {
            get {
                return ResourceManager.GetString("Brush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Brush_Defaults {
            get {
                return ResourceManager.GetString("Brush_Defaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Brush_Green {
            get {
                return ResourceManager.GetString("Brush_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Brush_Red {
            get {
                return ResourceManager.GetString("Brush_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Brush.
        /// </summary>
        internal static string Brush_Select {
            get {
                return ResourceManager.GetString("Brush_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Position.
        /// </summary>
        internal static string CameraPosition {
            get {
                return ResourceManager.GetString("CameraPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Settings.
        /// </summary>
        internal static string CameraSettings {
            get {
                return ResourceManager.GetString("CameraSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol count: {0}.
        /// </summary>
        internal static string CcResultParametrised_SymbolCount {
            get {
                return ResourceManager.GetString("CcResultParametrised_SymbolCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string CcResultParametrised_Symbology {
            get {
                return ResourceManager.GetString("CcResultParametrised_Symbology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC Type {0}.
        /// </summary>
        internal static string CcResultParametrised_Type {
            get {
                return ResourceManager.GetString("CcResultParametrised_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a color.
        /// </summary>
        internal static string Color_Select {
            get {
                return ResourceManager.GetString("Color_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Inverted.
        /// </summary>
        internal static string ColorInverted {
            get {
                return ResourceManager.GetString("ColorInverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous Scanning.
        /// </summary>
        internal static string ContinuousScanning {
            get {
                return ResourceManager.GetString("ContinuousScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        internal static string Controls {
            get {
                return ResourceManager.GetString("Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desired Torch State.
        /// </summary>
        internal static string DesiredTorchState {
            get {
                return ResourceManager.GetString("DesiredTorchState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Desired Torch State.
        /// </summary>
        internal static string DesiredTorchState_Select {
            get {
                return ResourceManager.GetString("DesiredTorchState_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimming (0.0 - 1.0) .
        /// </summary>
        internal static string Dimming {
            get {
                return ResourceManager.GetString("Dimming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable All.
        /// </summary>
        internal static string DisableAll {
            get {
                return ResourceManager.GetString("DisableAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled Color.
        /// </summary>
        internal static string DisabledColor {
            get {
                return ResourceManager.GetString("DisabledColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Disabled Color.
        /// </summary>
        internal static string DisabledColor_Select {
            get {
                return ResourceManager.GetString("DisabledColor_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dot Color.
        /// </summary>
        internal static string DotColor {
            get {
                return ResourceManager.GetString("DotColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Dot Color.
        /// </summary>
        internal static string DotColor_Select {
            get {
                return ResourceManager.GetString("DotColor_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable All.
        /// </summary>
        internal static string EnableAll {
            get {
                return ResourceManager.GetString("EnableAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled Color.
        /// </summary>
        internal static string EnabledColor {
            get {
                return ResourceManager.GetString("EnabledColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Enabled Color.
        /// </summary>
        internal static string EnabledColor_Select {
            get {
                return ResourceManager.GetString("EnabledColor_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions.
        /// </summary>
        internal static string Extensions {
            get {
                return ResourceManager.GetString("Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus Gesture Strategy.
        /// </summary>
        internal static string FocusGestureStrategy {
            get {
                return ResourceManager.GetString("FocusGestureStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Focus Gesture Strategy.
        /// </summary>
        internal static string FocusGestureStrategy_Select {
            get {
                return ResourceManager.GetString("FocusGestureStrategy_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Color.
        /// </summary>
        internal static string FrameColor {
            get {
                return ResourceManager.GetString("FrameColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Frame Color.
        /// </summary>
        internal static string FrameColor_Select {
            get {
                return ResourceManager.GetString("FrameColor_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestures.
        /// </summary>
        internal static string Gestures {
            get {
                return ResourceManager.GetString("Gestures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height and Width Aspec.
        /// </summary>
        internal static string HeightAndWidthAspect {
            get {
                return ResourceManager.GetString("HeightAndWidthAspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height Aspect.
        /// </summary>
        internal static string HeightAspect {
            get {
                return ResourceManager.GetString("HeightAspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laserline.
        /// </summary>
        internal static string Laserline {
            get {
                return ResourceManager.GetString("Laserline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Style.
        /// </summary>
        internal static string LineStyle {
            get {
                return ResourceManager.GetString("LineStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Line Style.
        /// </summary>
        internal static string LineStyle_Select {
            get {
                return ResourceManager.GetString("LineStyle_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longer Dimension Aspect.
        /// </summary>
        internal static string LongerDimensionAspect {
            get {
                return ResourceManager.GetString("LongerDimensionAspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looping.
        /// </summary>
        internal static string Looping {
            get {
                return ResourceManager.GetString("Looping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        internal static string Margin_Bottom {
            get {
                return ResourceManager.GetString("Margin_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string Margin_Left {
            get {
                return ResourceManager.GetString("Margin_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string Margin_Right {
            get {
                return ResourceManager.GetString("Margin_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        internal static string Margin_Top {
            get {
                return ResourceManager.GetString("Margin_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margins.
        /// </summary>
        internal static string Margins {
            get {
                return ResourceManager.GetString("Margins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        internal static string Maximum {
            get {
                return ResourceManager.GetString("Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Maximum.
        /// </summary>
        internal static string Maximum_Select {
            get {
                return ResourceManager.GetString("Maximum_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        internal static string Minimum {
            get {
                return ResourceManager.GetString("Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Minimum.
        /// </summary>
        internal static string Minimum_Select {
            get {
                return ResourceManager.GetString("Minimum_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay.
        /// </summary>
        internal static string Overlay {
            get {
                return ResourceManager.GetString("Overlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point of Interest.
        /// </summary>
        internal static string PointOfInterest {
            get {
                return ResourceManager.GetString("PointOfInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Resolution.
        /// </summary>
        internal static string PreferredResolution {
            get {
                return ResourceManager.GetString("PreferredResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Preferred Resolution.
        /// </summary>
        internal static string PreferredResolution_Select {
            get {
                return ResourceManager.GetString("PreferredResolution_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius.
        /// </summary>
        internal static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        internal static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangular.
        /// </summary>
        internal static string Rectangular {
            get {
                return ResourceManager.GetString("Rectangular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol count: {0}.
        /// </summary>
        internal static string ResultParametrised_SymbolCount {
            get {
                return ResourceManager.GetString("ResultParametrised_SymbolCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string ResultParametrised_Symbology {
            get {
                return ResourceManager.GetString("ResultParametrised_Symbology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Result.
        /// </summary>
        internal static string ScanResult {
            get {
                return ResourceManager.GetString("ScanResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode Capture.
        /// </summary>
        internal static string Setting_BarcodeCapture {
            get {
                return ResourceManager.GetString("Setting_BarcodeCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        internal static string Setting_Camera {
            get {
                return ResourceManager.GetString("Setting_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Duplicate Filter.
        /// </summary>
        internal static string Setting_CodeDuplicateFilter {
            get {
                return ResourceManager.GetString("Setting_CodeDuplicateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composite Types.
        /// </summary>
        internal static string Setting_CompositeTypes {
            get {
                return ResourceManager.GetString("Setting_CompositeTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        internal static string Setting_Controls {
            get {
                return ResourceManager.GetString("Setting_Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        internal static string Setting_Feedback {
            get {
                return ResourceManager.GetString("Setting_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestures.
        /// </summary>
        internal static string Setting_Gestures {
            get {
                return ResourceManager.GetString("Setting_Gestures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Selection.
        /// </summary>
        internal static string Setting_LocationSelection {
            get {
                return ResourceManager.GetString("Setting_LocationSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        internal static string Setting_Logo {
            get {
                return ResourceManager.GetString("Setting_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenSource License Information.
        /// </summary>
        internal static string Setting_OpenSourceLicenseInfo {
            get {
                return ResourceManager.GetString("Setting_OpenSourceLicenseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay.
        /// </summary>
        internal static string Setting_Overlay {
            get {
                return ResourceManager.GetString("Setting_Overlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point of Interest.
        /// </summary>
        internal static string Setting_PointOfInterest {
            get {
                return ResourceManager.GetString("Setting_PointOfInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string Setting_Result {
            get {
                return ResourceManager.GetString("Setting_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Area.
        /// </summary>
        internal static string Setting_ScanArea {
            get {
                return ResourceManager.GetString("Setting_ScanArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbologies.
        /// </summary>
        internal static string Setting_Symbologies {
            get {
                return ResourceManager.GetString("Setting_Symbologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string Setting_View {
            get {
                return ResourceManager.GetString("Setting_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewfinder.
        /// </summary>
        internal static string Setting_Viewfinder {
            get {
                return ResourceManager.GetString("Setting_Viewfinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shorter Dimension.
        /// </summary>
        internal static string ShorterDimension {
            get {
                return ResourceManager.GetString("ShorterDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shorter Dimension And Aspect Ratio.
        /// </summary>
        internal static string ShorterDimensionAndAspect {
            get {
                return ResourceManager.GetString("ShorterDimensionAndAspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should Show Scan Area Guides.
        /// </summary>
        internal static string ShouldShowScanAreaGuides {
            get {
                return ResourceManager.GetString("ShouldShowScanAreaGuides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Specification.
        /// </summary>
        internal static string SizeSpecification {
            get {
                return ResourceManager.GetString("SizeSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Size Specification.
        /// </summary>
        internal static string SizeSpecification_Select {
            get {
                return ResourceManager.GetString("SizeSpecification_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        internal static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        internal static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a style.
        /// </summary>
        internal static string Style_Select {
            get {
                return ResourceManager.GetString("Style_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe to Zoom.
        /// </summary>
        internal static string SwipeToZoom {
            get {
                return ResourceManager.GetString("SwipeToZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string Symbology_Disabled {
            get {
                return ResourceManager.GetString("Symbology_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string Symbology_Enabled {
            get {
                return ResourceManager.GetString("Symbology_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to Focus.
        /// </summary>
        internal static string TapToFocus {
            get {
                return ResourceManager.GetString("TapToFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torch Button.
        /// </summary>
        internal static string TorchButton {
            get {
                return ResourceManager.GetString("TorchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibration.
        /// </summary>
        internal static string Vibration {
            get {
                return ResourceManager.GetString("Vibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewfinder.
        /// </summary>
        internal static string Viewfinder {
            get {
                return ResourceManager.GetString("Viewfinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width and Height.
        /// </summary>
        internal static string WidthAndHeight {
            get {
                return ResourceManager.GetString("WidthAndHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width and Height Aspec.
        /// </summary>
        internal static string WidthAndHeightAspect {
            get {
                return ResourceManager.GetString("WidthAndHeightAspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width Aspect.
        /// </summary>
        internal static string WidthAspect {
            get {
                return ResourceManager.GetString("WidthAspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Factor.
        /// </summary>
        internal static string ZoomFactor {
            get {
                return ResourceManager.GetString("ZoomFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Gesture Zoom Factor.
        /// </summary>
        internal static string ZoomGestureZoomFactor {
            get {
                return ResourceManager.GetString("ZoomGestureZoomFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Switch Button.
        /// </summary>
        internal static string ZoomSwitchButton {
            get {
                return ResourceManager.GetString("ZoomSwitchButton", resourceCulture);
            }
        }
    }
}
